name: SonarQube Analysis
description: Run SonarQube analysis on the project
runs:
  using: composite
  steps:
    - run: ./gradlew sonarqube
      shell: bash
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}