name: Run Tests and Upload Report
description: Run tests and publish Junit report
runs:
  using: composite
  steps:
    - name: Run Tests
      run: cd my-gradle-project && ./gradlew test
      shell: bash
    - name: Upload Test Report
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: my-gradle-project/build/test-results/test