name: Create GitHub Release
description: Use Github ApI to create a release
runs:
  using: composite
  steps:
    - run: |
        VERSION=$(./gradlew -q printVersion)
        curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -d"{\"tag_name\": \"${VERSION}\", \"name\": \"Release ${VERSION}\", \"body\": \"Automated release from Jenkins\", \"draft\": false, \"prerelease\": false}" \
              https://api.github.com/repos/your-org/your-repo/releases