name: Upload to S3
description: Sync .jar to S3 bucket
runs:
  using: composite
  steps:
    - run: aws s3 cp build/libs/*.jar s3://your-bucket-name/path/ --region us-east-1
      shell: bash
    - run: echo "Artifact uploaded to S3 successfully."
      shell: bash
    