name: end-to-end workflow
description: End-to-end workflow for building, testing, and deploying code
on:
  workflow_dispatch:
    inputs:
      DEPLOY_ENV:
        description: 'Environment to deploy to'
        required: true
        default: dev
        type: choice
        options:
          - dev
          - staging
          - prod
jobs:
  bulid:
    runs-on: ubuntu-latest
    steps:
      - uses: ./actions/checkout
      - uses: ./actions/bulid
      - uses: ./actions/sonar
      - uses: ./actions/test-report
      - uses: ./actions/manual-approval
        with:
          Environment: ${{ github.event.inputs.DEPLOY_ENV }}
      - uses: ./actions/upload-artifact
      - uses: ./actions/sync-s3
      - uses: ./actions/ssh-deploy
      - uses: ./actions/github-release
      
